apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: <DOMAIN_METADATA_NAME>
spec:
  secretName: <DOMAIN_SECRET_NAME>
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: <DOMAIN_COMMON_NAME>
  dnsNames:
    - <DOMAIN>
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - <DOMAIN>
